### ISSUE TITLE
Direction arrows

### ISSUE THREAD

**Issue by kiarfuzzy** [ErisApps/HitScoreVisualizer#21]
Can you also implement the direction arrows from this one?

https://github.com/PulseLane/HitScoreVisualizer/tree/feature/direction-1.34

This should be a standard feature of HitScoreVisualizer, imo

**Comment by qqrz997** [comment]
i can potentially look into this feature after some internal reworking is done

**Comment by bleetube** [comment]
personally, when I tried it with direction arrows the feedback signal-to-noise  wasn't really useful unless I was playing true acc. In the end, choosing colors and showing the accuracy number (1-15) was much more useful. Definitely not opposed to it being added, but wouldn't give it priority

**Comment by kiarfuzzy** [comment]
in combination with a config that hides your best cuts, like the ones from electrostats, it becomes very useful to detect and improve your worst cuts

**Comment by qqrz997** [comment]
added this in 416cff07f649d67a83713c5b4ab41147f03c1adf

this is the same way that quest's HSV uses it.
