### ISSUE TITLE
bug report for 1.34.2hsv

### ISSUE THREAD

**Issue by RuoChennn** [ErisApps/HitScoreVisualizer#26]
I compiled branch # https://github.com/ErisApps/HitScoreVisualizer/commit/26dd59380fd2398cfbe338c7fe75497f0987a293, but it couldn't load the song properly in 1.34.2. However, I adjusted the hitscore bloom to false and the game can be loaded normally

**Comment by qqrz997** [comment]
i don't support versions other than latest, and this has been fixed in a later release.
