### ISSUE TITLE
Arcs leading into a chain head make HSV think the chain head has post-swing score

### ISSUE THREAD

**Issue by 1unar-Eclipse** [ErisApps/HitScoreVisualizer#27]
_(I'm using release 3.4.0. I have not tested this on 3.4.3 because modding as a whole is unstable for me on the latest Beat Saber release.)_

If a map has an arc that ends with a chain head, the mod will seemingly treat the chain head as a normal note, calculating and using the post-swing value even though it should always be 0 in vanilla. Active gameplay and BeatLeader replays both have this effect.

[Example config that has incorrect scores in red](https://github.com/user-attachments/files/17152206/Score_Config_-_Numbers.json)
To verify, https://beatsaver.com/maps/3bcb2 at 0:57 is an example that has an arc leading into a chain.

**Comment by qqrz997** [comment]
this is an issue with the game, those notes actually do give up to 115 points, you could even unselect a config and still see they do. ost maps don't use arcs into chains so it's probably not intended behaviour but to be honest this doesn't break anything and the arcs are just giving free score.

**Comment by qqrz997** [comment]
(p.s. as you mentioned it, the latest version is not technically supported for modding quite yet, but you technically could scrounge around github for all of the core mods)

**Comment by 1unar-Eclipse** [comment]
> this is an issue with the game, those notes actually do give up to 115 points, you could even unselect a config and still see they do. ost maps don't use arcs into chains so it's probably not intended behaviour but to be honest this doesn't break anything and the arcs are just giving free score.

Would it be possible to make chain heads with arcs like this use normal notes' HSV parameters, then? They are acting as normal notes, so it doesn't make much sense to make them use chain head judgements.

**Comment by qqrz997** [comment]
a chain note is a chain note, the mod sees it as a chain note. i could see but it's literally just a chain note with post swing.

**Comment by ibillingsley** [comment]
As a silly workaround, in my configs I have chainHeadJudgments all the way up to 115, with both 85 and 115 colored as if they're perfect. It can still be misleading if you score 85 or lower on one of the arc chain heads but that's extremely rare.
